sudo: false
language: java
jdk:
  - oraclejdk7
env:
  matrix:
    #- ACCUMULO_VERSION='1.5.2'              HADOOP_VERSION='2.6.0'              GEOTOOLS_VERSION='11.5'   GEOSERVER_VERSION='2.5.5' PLATFORM_VERSION='""'
    #- ACCUMULO_VERSION='1.6.0-cdh5.1.4'     HADOOP_VERSION='2.5.0-cdh5.3.2'     GEOTOOLS_VERSION='12.2'   GEOSERVER_VERSION='2.6.2' PLATFORM_VERSION='cloudera'
    - ACCUMULO_VERSION='1.6.2'              HADOOP_VERSION='2.6.0'              GEOTOOLS_VERSION='12.2'   GEOSERVER_VERSION='2.6.2' PLATFORM_VERSION='""'
    #- ACCUMULO_VERSION='1.6.1.2.2.0.0-2041' HADOOP_VERSION='2.6.0.2.2.0.0-2041' GEOTOOLS_VERSION='12.2'   GEOSERVER_VERSION='2.6.2' PLATFORM_VERSION='hortonworks'
  global:
    #github token
    - secure: "TosKDl5mnt8UKeyWDg65i6cWENR7EorQbFPSvZ5ZfQfAaDAOeIN2OA/zxtRMELeYM82+n+GGXQOt0qPiYqyRlufYJJSUnWiwvI5gm3a8+f58atcU2R2bF9jd81bsL9jCS+JCQxAmzh8FCO6t7DJ4OdoMyMaIR7XjlSlsIJ97dd8="
cache:
  directories:
  - $HOME/.m2
install: "mvn -q clean install javadoc:aggregate -Dfindbugs.skip -Daccumulo.version=${ACCUMULO_VERSION} -Dhadoop.version=${HADOOP_VERSION} -Dgeotools.version=${GEOTOOLS_VERSION} -Dgeoserver.version=${GEOSERVER_VERSION} -DskipITs=true -DskipTests=true -P ${PLATFORM_VERSION};"
script: "mvn -q verify -Daccumulo.version=${ACCUMULO_VERSION} -Dhadoop.version=${HADOOP_VERSION} -Dgeotools.version=${GEOTOOLS_VERSION} -Dgeoserver.version=${GEOSERVER_VERSION} -P ${PLATFORM_VERSION}"
before_install:
  - export MAVEN_OPTS="-Xmx512m -XX:MaxPermSize=192m"
  - chmod +x .utility/maven-coveralls-hack.sh
  - .utility/maven-coveralls-hack.sh



addons:
  coverity_scan:
    project:
      name: "ngageoint/geowave"
      description: "Build submitted via Travis CI"
    notification_email: chris@slowcar.net
    build_command_prepend: "mvn clean"
    build_command: "mvn clean compile -Dfindbugs.skip -Daccumulo.version=${ACCUMULO_VERSION} -Dhadoop.version=${HADOOP_VERSION} -Dgeotools.version=${GEOTOOLS_VERSION} -Dgeoserver.version=${GEOSERVER_VERSION} -DskipITs=true -DskipTests=true -P ${PLATFORM_VERSION}"
    branch_pattern: coverty_scan
